name: minimal test
# Tests the pipeline with a minimal dataset
on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

jobs:
  test:
    name: Run pipeline with test data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"
      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} --pod5 ${{ github.workspace }}/test/pod5/ --ref ${{ github.workspace }}/test/ref.fasta -profile test
